### ISSUE TITLE
Link to advanced CIFAR model is broken in README

### ISSUE THREAD

**Issue by ThomasKluiters** [larq/larq#431]
### Describe the bug
The README links to https://docs.larq.dev/larq/tutorials/binarynet_advanced_cifar10/ which no longer exists.

### To Reproduce
1. Go to https://github.com/larq/larq
2. Click on "BinaryNet on CIFAR10 (Advanced)" in the README 

### Expected behavior
I expect to be shown documentation for "BinaryNet on CIFAR10 (Advanced)"

### Environment
Chrome

TensorFlow version:  x
Larq version: x

**Comment by AdamHillier** [comment]
Hi, thank you very much for your interest in Larq!

We recently updated our docs and removed this particular tutorial because it was no longer relevant after recent API changes to Larq. We must have missed that reference to it in the README, thank you for pointing it out; I will go and remove it now.

Hopefully you'll find the other two tutorials useful.

**Comment by AdamHillier** [comment]
Closed by #432
