### ISSUE TITLE
Bug in DoReFa quantizer

### ISSUE THREAD

**Issue by FerranLisa** [larq/larq#484]
### Describe the bug

expression "n = 2 ** self.precision - 1" seems wrong
it should be "n = 2 ** self.precision"
or "n = 2 ** (self.precision - 1)"
### Expected behavior

Value of "n" should be a power of 2

### Environment

TensorFlow version: 
Larq version:

**Comment by jneeven** [comment]
Hi, thank you for opening this issue! Why do you think `n` should be a power of 2?
In the [DoReFa paper](https://arxiv.org/abs/1606.06160), their quantization function is described as follows:

![image](https://user-images.githubusercontent.com/19648598/81042129-b8425f80-8eaf-11ea-857c-08216055190b.png)

So you see that they indeed use `n = 2 ** self.precision - 1`, which is not a power of two. This makes a lot of sense: let's assume you want to quantize values to 2-bit unsigned integers. Then the possible values after quantizations are 0, 1, 2, and 3. The 3 here corresponds to the formula above: `3 = 2 ** 2 - 1`. Now of course DoReFa doesn't quantize to unsigned integers, but rather to real-valued intervals between 0 and 1. This is illustrated nicely in our [documentation](https://docs.larq.dev/larq/api/quantizers/#dorefa):
![image](https://user-images.githubusercontent.com/19648598/81042399-51717600-8eb0-11ea-849d-0d68ec2ef602.png)

As you can see in the forward pass, the values are quantized as follows:
```python
if x < 0.25:
     q_x = 0
elif x < 0.5:
    q_x = 0.33
elif x < 0.75:
    q_x = 0.66
else:
    q_x = 1
```

So while `n` is 3, we end up with **four** different quantization levels, because we also include the zero. If we would set `n = 4`, we would end up with **five** different quantization levels, which would no longer be representable using only 2 bits.

Since our implementation follows the paper I will close this issue, but if you have any more questions, feel free to reach out to us on [our spectrum chat](https://spectrum.chat/larq)!
