### ISSUE TITLE
Speed Benchmarks of Inference

### ISSUE THREAD

**Issue by ogencoglu** [larq/larq#502]
### Feature motivation
Would be nice to have a detailed comparison of inference speed performance between standard architectures and binarized ones across different devices.

### Feature description
No functional changes required. A script should be enough.

**Comment by koenhelwegen** [comment]
Hi @ogencoglu, thanks for the suggestion! Indeed, this is easy to add and we've been thinking about publishing these numbers. However, it is a bit tricky because architectures tend to have specialized features that LCE has not been optimized for, potentially skewing the results. In general, the [QuickNet family](https://docs.larq.dev/compute-engine/#performance) currently provides the best accuracy/latency trade-off on Armv8-a devices such as the Pixel 1. We may add benchmark results for more models in the future if it seems useful for the field.

**Comment by lgeiger** [comment]
@koenhelwegen benchmarked all of publicly available Larq Zoo in https://github.com/larq/docs/pull/149.

We now have latencies measured on Pixel 1 for these models available at https://docs.larq.dev/zoo/#available-models, this should make it easier to compare against existing models.
@ogencoglu I'm closing the issue for now, feel free to reopen if you have more comments.
