### ISSUE TITLE
Binary weights disappear after saving a model with binary weights - and realoding it

### ISSUE THREAD

**Issue by guyam2** [larq/larq#553]
### Describe the bug
**After _model.save(..)_ in the _**with larq.context.quantized_scope(True)**_  scope  and reloading the model - the binary weights are gone (and replaced with the unwanted real-valued weights)**

### To Reproduce
Hi, I created a BNN with 5 layers (each layer is Batch-Norm as then lq.layer.QuantDense layers). I trained the BNN and then opened a with _larq.context.quantized_scope(True) scope_. Inside the scope when I do _get_weights()_ then the binary weights are indeed presented, and then I call model.save(..)_. Later I upload the model and the bianry weights dissappear - and instead I have real non-binary weights. **_I'm attaching the code_**

### Expected behavior
I expected that after saving the model (in the _with larq.context.quantized_scope(True) _ scope) and reloading it - the loaded model will have binary weights.

### Environment

TensorFlow version:  **2.3** (and also 2.1)
Larq version: **latest (0.10)**
![larw_bug](https://user-images.githubusercontent.com/60099459/90344006-741e3980-e01e-11ea-8a47-c37f7ce9a893.PNG)

Thank you in advance, for the help!

**Comment by lgeiger** [comment]
Larq represents quantized/binary variables using a `QuantizedVariable` which encodes the underlying [latent weights](https://docs.larq.dev/larq/guides/bnn-optimization/#latent-weights) together with a quantizer that will quantize the full precision weights in the forward pass.

As far as I can tell this is consistent with saving and loading a model in order to have the reloaded models behave exactly like the original one. You should be able to check this in your code example by running:
```python
print(loaded.weights)  # prints full precision latent weights
with lq.context.quantized_scope(True):
    print(loaded.weights)  # prints quantized weights
```

So I don't fully understand what you mean with "the binary weights dissappear" as it is expected that the underlying latent weights are full precision. This behaviour is important as it ensures that training can be resumed from reloaded models.

Due to the way TensorFlow handles model saving in the `.h5` format (it stores the numpy values of `model.get_weights()`) in contrast to the "saved model" format (stores the TensorFlow variables), you are able to export the binarized variables when saving the model using `model.save("quantized_model.h5")` or `model.save("quantized_model", save_format="h5")` inside a quantized scope. However, this usage is highly discouraged as it can lead to unexpected behaviour in cases where `quantizer(x) != quantizer(quantizer(x))` as the quantizer then will be applied twice (once when exporting the weights and once during the normal forward pass of the reloaded model).

If you want to export the model for inference with truely binary bitpacked weights, I'd recommend [Larq Compute Engine](https://docs.larq.dev/compute-engine/api/converter/) instead which will convert the model to an inference version in the TFLite format.

Please let me know if that answers your question.

**Comment by guyam2** [comment]
Hi Leon

Yes, I agree understand that when saving in the **with lq.context.quantized_scope(True)** will allow saving a "h5" format, and the point is that the loaded model can resume training and thus the binarization/non-binarization of weights depends on being in/out of th **with lq.context.quantized_scope(True):** scope.

I'll emphasize my question -
**for my purposes I have to have the networks saved in the "save_model" format** (not the "h5" one), **and I do not need to resume training at all** - thus I have no need for the latent weights and really prefer keeping the binary weights "for good", and in the saved_model format.


Is that possible?

**Comment by lgeiger** [comment]
Sure, if want to remove the latent variables I'd recommend to explicitely convert them before saving using:
```python
with lq.context.quantized_scope(True):
    model.set_weights(model.get_weights())  # remove latent weights
```

This will make it explicit and will work with all saving formats.

**Comment by guyam2** [comment]
Thank you!

**Comment by lgeiger** [comment]
> Thank you!

Glad that solution work for you 👍

**Comment by guyam2** [comment]
Oh and just making sure one last thing Lucas - writing the code you left will not lead to the unwanted behaivour you mentioned in youre first comment, correct? :) 
(in which you said saving is sometimes "discouraged")

**Comment by lgeiger** [comment]
> writing the code you left will not lead to the unwanted behaivour you mentioned in youre first comment, correct? :)

If you are using `ste_sign` (or any other quantizer where `quantizer(x) == quantizer(quantizer(x))` this is completely fine to do.
If that's not the case (should be pretty rare) I'd recommend to build a new model with `kernel_quantizer=None` and assign the quantized weights to that one using `model.set_weights` which prevent's having unnecessary kernel quantizers in the saved model.
