### ISSUE TITLE
__version__

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/larq#595]
### Feature motivation
Is there a way to dynamically poll the version of larq (or lce or larq-zoo for that matter)?
If not, could it be done using `__version__` as usual for standard library modules?

### Feature description
```
import larq
print(larq.__version__)
```

**Comment by lgeiger** [comment]
Currently we don't have a `__version__` identifier in larq, but I agree that it would be good to add since many other Python packages adhere to this convention as well.

Would you like to send a PR to fix this? Probably the first solution mentioned in https://packaging.python.org/guides/single-sourcing-package-version/ is the easiest to maintain, but I'm not sure what the general best practices here are.

In the meantime you can retrieve the version using:
```python
from importlib import metadata;
print(metadata.version("larq"))
```

**Comment by AdamHillier** [comment]
Oops, had just finished #596 when you commented @lgeiger.

**Comment by lkindrat-xmos** [comment]
That was quick, thanks gents!
