### ISSUE TITLE
LCE Inference of QuickNet slower than BenchMark

### ISSUE THREAD

**Issue by Chidhambararajan** [larq/larq#607]
### Describe the bug
I tried to benchmark the Quicknet Model in my laptop and it was slower than the benchmark results in Larq Zoo Page

### To Reproduce
```
import larq_compute_engine as lce
import numpy as np
import larq_zoo as lqz
import time
import tensorflow as tf

tf.config.set_visible_devices([], 'GPU')#Using only CPU

model = lqz.sota.QuickNet()
t = np.random.rand(1,224,224,3).astype(np.float32)
lce_model = lce.convert_keras_model(model)
interpreter = lce.testing.Interpreter(lce_model,4)

#LCE Inference BenchMark
interpreter.predict(t,1) #LCE Inference
s=time.time()
for i in range(1000):
    interpreter.predict(t,1) #LCE Inference
e = time.time()
old =(e-s)

model.predict(t) # Keras Inference
s=time.time()
for i in range(1000):
    model.predict(t) #Keras Inference
e=time.time()

print("Keras Inference:",(e-s)/1000)
print("LCE Inference  :",old/1000)
```

### Expected behavior
I got the following output in python3.8.5
```
Keras Inference: 0.0856881742477417
LCE Inference  : 0.10119180631637573
```
In python3.6
```
Keras Inference: 0.07112254023551941
LCE Inference  : 0.09584478735923767
```

The LarqZoo page says that the **_QuickNet() single thread_** model takes 27.3ms on pixel2 , but my **_QuickNet() 4 thread_** inference takes 85ms 

Shouldn't the 4thread model run more faster in laptop than the single thread model on  pixel2
Am I doing it wrong??

### Environment
Note that all these packages weren't built in the system and were installed from wheels by pip
```
larq==0.10.2
larq-compute-engine==0.4.3
larq-zoo==2.0.3
tensorflow==2.4.0
python3.8.5 or python3.6.11
```

What should be done , to get the benchmark speeds ?
Thanks for the awesome library

**Comment by jneeven** [comment]
Hi! Thanks for your interest in Larq and happy new year! The results you obtain are expected; it appears you're using the python-wrapped test-only version of the LCE interpreter (`lce.testing.Interpreter`). This code only uses reference implementations for all the kernels, so it isn't optimized in any way at all, and is only intended for testing purposes (I admit that this is unclear from the documentation, sorry about that).

The actual LCE interpreter is optimized for the ARM v8 architecture, used by e.g. a Raspberry Pi or various Android phones. It is therefore unlikely to run very efficiently on your laptop, since for different instruction set architectures (e.g. Intel x86) it will again default to the reference implementations. Since BNNs are most promising for deep learning on edge devices, ARM v8 is a more promising platform for us to focus on in terms of practical applications. As of now, we unfortunately have no concrete plans to port LCE to "laptop architectures" such as x86 (the optimizations would be very different from those on ARM v8), but feel free to make a contribution to LCE if you need it! For an example of the kind of code involved, see [this community PR](https://github.com/larq/compute-engine/pull/432) from last year.

To run your BNNs at optimal efficiency, I'd therefore suggest running LCE on an ARM-based device if possible, for which we have prebuilt benchmarking binaries available: https://docs.larq.dev/compute-engine/benchmark/

**Comment by Chidhambararajan** [comment]
Got it , Thanks!!
