### ISSUE TITLE
Conversion between Keras and larq model

### ISSUE THREAD

**Issue by mervess** [larq/larq#699]
I've noticed that Keras' _Conv2D_ and larq's _QuantConv2D_ layers are used together in this [tutorial](https://docs.larq.dev/compute-engine/end_to_end/). Is it just a use case of the library to emphasize its versatility? What may be the outcome and how does such use case affect a BinaryNet model overall?

Also, do you have any _tf.Keras_ to _larq_ automatic model converter (for on PC use, not as _TFLite_), or have a future idea to do so?

**Comment by AdamHillier** [comment]
Hi @mervess, thanks for your interest in Larq!

Binarised models often include non-binary layers as well. This is particularly common in the first and/or last layers, as is the case for the example model in the tutorial you linked to. Larq is fully compatible with all of the usual non-quantised Keras layers, so they can be intermixed freely in this way to get models that include both quantised and non-quantised layers.

In addition, `lq.layers.QuantConv2D` is a subclass of `tf.keras.layers.Conv2D`. If you use a `QuantConv2D` layer without passing in a `input_quantizer` or `kernel_quantizer`, it acts as a non-quantised convolution layer with the exact same behaviour as you would get if you'd instead used a `Conv2D`. The same is analagously true of `QuantConv1D`, `QuantDense`, et cetera.

While it's possible to use Larq `Quant____` layers in this way to model non-quantised layers, we often will use the Keras equivalents directly instead. I think it helps with code readability too, because it's then clearer which layers are quantised and which are not.

I hope that helps!

**Comment by mervess** [comment]
Yes, indeed.
Many thanks @AdamHillier!
