### ISSUE TITLE
MACs of a tf-lite model

### ISSUE THREAD

**Issue by mervess** [larq/larq#732]
As a fan of the function `lq.models.summary(model)`*, I was wondering if it is somehow applicable onto _tf-lite_ models as well.

I assume the summary would be the same if a binarised _Keras_ model and a _tf-lite_ model have the same origin, meaning the _tf-lite_ model is converted from the _Keras_ model via _larq-compute-engine_. However, I'm looking to see the summary of any _tf-lite_ model, if possible.

Is it possible?

*I like that it shows the MACs, model size and everything. Good thought on that by the way!

**Comment by jneeven** [comment]
Hi, glad you like the model summary! Very good question, it would be awesome if there was a similar way to obtain a model summary for a TFLite file. As you mentioned, our Keras summaries are already targeted at describing the MACs etc in the converted TFLite model, so unfortunately this is not something we've needed so far and is not part of Larq. This would technically also be somewhat tricky because while parsing a TFLite flatbuffer in Python is definitely possible, it's a lot less straightforward than parsing a Keras model... Unfortunately I don't have concrete code I can share here to showcase how that would work, but [this library](https://github.com/jackwish/tflite/blob/master/tflite/SubGraph.py) gives you a good idea of what the flatbuffer Python schema looks like.

To look at / debug converted models, I can recommend [Netron](https://netron.app/), as it supports both `.tflite` and `.h5` files, and is at least a unified interface in that sense. Unfortunately it doesn't provide any kind of summary though; it's more focused on showing architectural details. In a quick search I did find [this flatbuffer analysis tool](https://github.com/eliberis/tflite-tools#example-output), maybe that's useful to you?

**Comment by mervess** [comment]
Many thanks for the informative reply @jneeven!
I use Netron, and am going to look into the other helpful links you mention.

I only came across [tflite-flops](https://github.com/lisosia/tflite-flops) which offers an estimated measurement, yet it does not have sufficient layer support for my models. Sharing it here in case someone else has a similar question to mine and it may be useful for them.
